//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTestimonial
    {
        public int testimonialId { get; set; }
        public string testimonialName { get; set; }
        public string testimonialTitle { get; set; }
        public string testimonialDescription { get; set; }
        public string testimonialImageUrl { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
